services:
  - type: web
    name: quizhub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn QuizHubProject.wsgi:application
    envVars:
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromSecret: SUPABASE_DB_URL